from turtle import *
def main():
    tu=bgcolor("lavender")
    tu=Turtle()
    tu.shape("turtle")
    tu.speed("fast")

    tu.up()
    tu.color("red")
    tu.goto(250, 0)
    tu.lt(90)
    tu.begin_fill()
    tu.circle(240, 360)
    tu.end_fill()
    tu.home()

    tu.up()
    tu.color("dark orange")
    tu.goto(230, 0)
    tu.lt(90)
    tu.begin_fill()
    tu.circle(220, 360)
    tu.end_fill()
    tu.home()

    tu.up()
    tu.color("yellow")
    tu.goto(210, 0)
    tu.lt(90)
    tu.begin_fill()
    tu.circle(200, 360)
    tu.end_fill()
    tu.home()

    tu.up()
    tu.color("springGreen")
    tu.goto(190, 0)
    tu.lt(90)
    tu.begin_fill()
    tu.circle(180, 360)
    tu.end_fill()
    tu.home()

    tu.up()
    tu.color("cyan")
    tu.goto(170, 0)
    tu.lt(90)
    tu.begin_fill()
    tu.circle(160, 360)
    tu.end_fill()
    tu.home()

    tu.up()
    tu.color("CornFlowerBlue")
    tu.goto(150, 0)
    tu.lt(90)
    tu.begin_fill()
    tu.circle(140, 360)
    tu.end_fill()
    tu.home()

    tu.up()
    tu.color("magenta")
    tu.goto(130, 0)
    tu.lt(90)
    tu.begin_fill()
    tu.circle(120, 360)
    tu.end_fill()
    tu.home()

    tu.up()
    tu.color("lavender")
    tu.goto(110, 0)
    tu.lt(90)
    tu.begin_fill()
    tu.circle(100, 360)
    tu.end_fill()
    tu.home()

    tu.up()
    tu.goto(0, 120)
    tu.lt(90)
    tu.begin_fill()
    tu.dot(60, "white")
    tu.end_fill()
    tu.goto(40, 120)
    tu.dot(60, "white")
    tu.goto(80, 120)
    tu.dot(60, "white")
    tu.goto(100, 90)
    tu.dot(60, "white")
    tu.goto(50, 80)
    tu.dot(60, "white")
    tu.goto(10, 80)
    tu.dot(60, "white")
    tu.goto(-20, 90)
    tu.dot(60, "white")
    tu.goto(0, 90)
    tu.dot(10, "pink")
    tu.goto(80, 90)
    tu.dot(10, "pink")
    tu.goto(65, 110)
    tu.dot(15, "black")
    tu.goto(20, 110)
    tu.dot(15, "black")
    tu.goto(65, 106)
    tu.dot(15, "white")
    tu.goto(20, 106)
    tu.dot(15, "white")
    tu.home()
    tu.color("black")
    tu.goto(35, 80)
    tu.right(90)
    tu.begin_fill()
    tu.circle(10, 180)
    tu.end_fill()
    tu.goto(45, 80)
    tu.dot(15, "white")
    tu.home()

    tu.color("lavender")
    done()
main()